spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product_management_test_db
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
